config/routes.rb
Rails.application.routes.draw do

  resources :foods, only: [:index, :show]
  resources :nutrients, only: [:index, :show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :nutrients
end

app/models/nutrient.rb
class Nutrient < ApplicationRecord
  belongs_to :food
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food=Food.find(params[:id])
  end





end

app/controllers/nutrients_controller.rb
class NutrientsController < ApplicationController

def index
  @nutrients = Nutrient.all
end


def show
  @nutrient = Nutrient.find(params[:id])
end


def new
  @nutrient = Nutrient.new
end

def create
  @nutrient = Nutrient.new(nutrient_params)
  if @nutrient.save
    redirect_to @nutrient
  else
    render :new
  end
end

def edit
  @nutrient = Nutrient.find(params[:id])
end


def update
    @nutrient = Nutrient.find(params[:id])
  if @nutrient.update(nutrient_params)
    redirect_to @nutrient
  else
    render :edit
  end
end


  private
  def nutrient_params
    params.require(:nutrient).permit(:name, :food_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foodds/edit.html.erb
<%=form_for @foodd do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.collection_select nutrient_id, Nutrient.all, :id, :name %>
<%= f.submit %>
<% end %>

app/views/foodds/index.html.erb
<%foodds.each do |foodd|%>
<li><%=link_to foodd.name, foodd_path(foodd)%><li>
  <%end%>

app/views/foodds/show.html.erb
<h1><%=foodd.name%></h1>

<ul>
  <%@foodd.nutrients.each do |nutrient|%>
  <li><%=link_to nutrient.name, nutrient_path(nutrient)%></li>
  <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nutrients/index.html.erb
<ol><% nutrients.each do |nutrient|%>
  <li> <%= link_to nutrient.name, nutrient_path(nutrient)%><li>
    <%end%>
  </ol>

  

app/views/nutrients/new.html.erb
<%=form_for @nutrients do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.collection_select food_id, Foodd.all, :id, :name %>
<%= f.submit %>
<% end %>

app/views/nutrients/show.html.erb
<h1><%=nutrient.name%> - Belongs To
  <%=link_to @nutrient.foodd.name, foodd_path(nutrient.foodd)%></h1>
  <h3><%=nutrient.name%></h3>